### ISSUE TITLE
Selecting char and then clicking off causes crash

### ISSUE THREAD

**Issue by ChromaQ** [altintx/urban-memory#1]
When I select the "character" and then click off of it without correctly using an action, the API appears to crash.

**Reproduction Steps:**
1. Click character
2. Click elsewhere - a different tile, etc. 

Results in urban-memory Docker container exiting, requires a manual restart of container.

Results in this Docker error:

```
parseCharacter
cacheCharacter {
  operator: { name: 'bob', operatorId: 'affe525a-1140-4c13-bfd1-d22d1970d31a' },
  class: {
    name: Translatable { translations: [Object] },
    ap: 2,
    maxAp: 6,
    initiativeModifier: NaN
getOperator is deprecated, should look up by operator uuid instead of socket id
TypeError: Cannot read properties of undefined (reading 'game')
    at /app/src/websocket/game/events/tile_interaction.ts:18:27
    at step (/app/src/websocket/game/events/tile_interaction.ts:33:23)
    at Object.next (/app/src/websocket/game/events/tile_interaction.ts:14:53)
    at fulfilled (/app/src/websocket/game/events/tile_interaction.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

**Comment by ChromaQ** [comment]
It seems like just re-clicking the avatar again also causes a crash. oopsie
